import TextCategory from "../../types/TextCategory";
import TextState from "../../types/TextState";

const testData: TextCategory[] = [
    {
      idTenant: "1",
      idCategory: "NumberOne",
      language: "Italian",
      isDefault: true,
      List: [
        {
        id: "1",
        text: "Questo è il primo testo",
        state: TextState.toBeTranslated,
        feedback: "Questo testo potrebbe essere migliorato",
        comment: "Non sono sicuro della traduzione",
        link: "https://www.example.com/text/1",
        },
      ],
    },
    {
        idTenant: "1",
        idCategory: "NumberTwo",
        language: "English",
        isDefault: true,
        List: [
          {
          id: "1",
          text: "Questo è il primo testo",
          state: TextState.toBeTranslated,
          feedback: "Questo testo potrebbe essere migliorato",
          comment: "Non sono sicuro della traduzione",
          link: "https://www.example.com/text/1",
          },
          {
          id: "2",
          text: "Questo è il secondo testo",
          state: TextState.toBeVerified,
          feedback: "Questa traduzione sembra essere corretta",
          comment: "Ho verificato la traduzione con un madrelingua",
          link: "https://www.example.com/text/2",
          },
          {
            id: "1",
            text: "Questo è il primo testo",
            state: TextState.toBeTranslated,
            feedback: "Questo testo potrebbe essere migliorato",
            comment: "Non sono sicuro della traduzione",
            link: "https://www.example.com/text/1",
            },
            {
            id: "2",
            text: "Questo è il secondo testo",
            state: TextState.toBeVerified,
            feedback: "Questa traduzione sembra essere corretta",
            comment: "Ho verificato la traduzione con un madrelingua",
            link: "https://www.example.com/text/2",
            },
        ],
      },
      {
        idTenant: "1",
        idCategory: "NumberThree",
        language: "Italian",
        isDefault: true,
        List: [
          {
          id: "1",
          text: "Questo è il primo testo",
          state: TextState.toBeTranslated,
          feedback: "Questo testo potrebbe essere migliorato",
          comment: "Non sono sicuro della traduzione",
          link: "https://www.example.com/text/1",
          },
          {
          id: "2",
          text: "Questo è il secondo testo",
          state: TextState.toBeVerified,
          feedback: "Questa traduzione sembra essere corretta",
          comment: "Ho verificato la traduzione con un madrelingua",
          link: "https://www.example.com/text/2",
          },
          {
            id: "1",
            text: "Questo è il primo testo",
            state: TextState.toBeTranslated,
            feedback: "Questo testo potrebbe essere migliorato",
            comment: "Non sono sicuro della traduzione",
            link: "https://www.example.com/text/1",
            },
            {
            id: "2",
            text: "Questo è il secondo testo",
            state: TextState.toBeVerified,
            feedback: "Questa traduzione sembra essere corretta",
            comment: "Ho verificato la traduzione con un madrelingua",
            link: "https://www.example.com/text/2",
            },
            {
              id: "1",
              text: "Questo è il primo testo",
              state: TextState.toBeTranslated,
              feedback: "Questo testo potrebbe essere migliorato",
              comment: "Non sono sicuro della traduzione",
              link: "https://www.example.com/text/1",
              },
              {
              id: "2",
              text: "Questo è il secondo testo",
              state: TextState.toBeVerified,
              feedback: "Questa traduzione sembra essere corretta",
              comment: "Ho verificato la traduzione con un madrelingua",
              link: "https://www.example.com/text/2",
              },
              {
                id: "1",
                text: "Questo è il primo testo",
                state: TextState.toBeTranslated,
                feedback: "Questo testo potrebbe essere migliorato",
                comment: "Non sono sicuro della traduzione",
                link: "https://www.example.com/text/1",
                },
                {
                id: "2",
                text: "Questo è il secondo testo",
                state: TextState.toBeVerified,
                feedback: "Questa traduzione sembra essere corretta",
                comment: "Ho verificato la traduzione con un madrelingua",
                link: "https://www.example.com/text/2",
                },
                {
                  id: "1",
                  text: "Questo è il primo testo",
                  state: TextState.toBeTranslated,
                  feedback: "Questo testo potrebbe essere migliorato",
                  comment: "Non sono sicuro della traduzione",
                  link: "https://www.example.com/text/1",
                  },
                  {
                  id: "2",
                  text: "Questo è il secondo testo",
                  state: TextState.toBeVerified,
                  feedback: "Questa traduzione sembra essere corretta",
                  comment: "Ho verificato la traduzione con un madrelingua",
                  link: "https://www.example.com/text/2",
                  },
        ],
      },
  ];
  
  export default testData;
  